//
// Created by Lennart Schink on 23.10.23.
//

#ifndef FEIG_RFIDREADERINTERFACE_BASICTCPCONNECT_H
#define FEIG_RFIDREADERINTERFACE_BASICTCPCONNECT_H


#endif //FEIG_RFIDREADERINTERFACE_BASICTCPCONNECT_H


